apiVersion: v1
kind: ServiceAccount
metadata:
  name: podagent
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podagent
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups: # for the network-crd used by kactus
      - "extensions"
      - "kaloom.com"
    resources:
      - networks
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podagent
roleRef:
  kind: ClusterRole
  name: podagent
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: podagent
  namespace: kube-system
